- job:
    block-downstream: false
    block-upstream: false
    builders:
    - copyartifact:
        exclude-pattern: null
        filter: '**/*/kubeconfig,cluster-config.txt,cluster-dir.tar.gz'
        flatten: true
        project: dev-svc-create-daily-custer-4.6
        target: '4.6'
        which-build: last-successful
    - copyartifact:
        exclude-pattern: null
        filter: '**/*/kubeconfig,cluster-config.txt,cluster-dir.tar.gz'
        flatten: true
        project: dev-svc-create-daily-custer-4.7
        target: '4.7'
        which-build: last-successful
    - copyartifact:
        exclude-pattern: null
        filter: '**/*/kubeconfig,cluster-config.txt,cluster-dir.tar.gz'
        flatten: true
        project: dev-svc-create-daily-custer-4.8
        target: '4.8'
        which-build: last-successful
    concurrent: false
    disabled: false
    name: dev-svc-cluster-latest-kubeconfig
    project-type: freestyle
    properties:
    - copyartifact:
        projects: update-secrets_rose-sanbox-1
    - build-discarder:
        artifact-days-to-keep: -1
        artifact-num-to-keep: -1
        days-to-keep: -1
        num-to-keep: 1
    publishers:
    - archive:
        allow-empty: false
        artifacts: '**/*'
        case-sensitive: true
        default-excludes: true
        fingerprint: true
        only-if-success: false
    - fingerprint:
        files: kubeconfig
        record-artifacts: true
    triggers:
    - reverse:
        jobs: dev-svc-create-daily-custer-4.6, dev-svc-create-daily-custer-4.7, dev-svc-create-daily-custer-4.8
    wrappers: []
